name: test
on:
  push:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: .npm
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - uses: devcontainers/ci@a56d055efecd725e8cfe370543b6071b79989cc8
        with:
          push: never
          runCmd: |
            npm test
            npm run prod
