name: test
on:
  push:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633

      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: .npm
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - uses: devcontainers/ci@7957e0cf6d027a8ab027745f399fcdbd3aa74f0f
        with:
          push: never
          runCmd: |
            npm test
            npm run prod
